#!/bin/sh

## Script to create a cinder project.

# Locations of important things..

CINDER_DIR="$HOME/Dropbox/dev/libraries/Cinder"
BASIC_APP_DIR="$CINDER_DIR/samples/BasicApp"

# Check to make sure that a name was given

if [ $# -eq 0 ]
  then
    echo "Correct usage is 'create-cinder-project [project-name]'"
fi

# Copy the folder to the current directory
PROJECT_NAME=$1
cp -R "$BASIC_APP_DIR" "$PWD/$PROJECT_NAME"

# Replace all instances of "BasicApp" with "$PROJECT_NAME"
# in the future, this should parse the template xml, probably in python

cd $PROJECT_NAME
mv src/BasicApp.cpp "src/$PROJECT_NAME.cpp"

sed -i 's|BasicApp|'"$PROJECT_NAME"'|g' "src/$PROJECT_NAME.cpp" proj/cmake/CMakeLists.txt

# Fix the path of CINDER in the cmake file
sed -i '6d;5 a get_filename_component( CINDER_PATH "'"$CINDER_DIR"'" ABSOLUTE )' proj/cmake/CMakeLists.txt
