#!/bin/sh

# Launches a debug build of a cinder project.
# runs cinder-gen-makefile and cinder-build if necessary.
# must be run in the root directory of a cinder project
# created with cinder-create

if [ ! -d "proj/cmake/build/Debug" ]; then
  cinder-build
fi

PROJECT_NAME=${PWD##*/}

EXECUTABLE=./proj/cmake/build/Debug/$PROJECT_NAME/$PROJECT_NAME
MAC_EXECUTABLE=$EXECUTABLE.app/Contents/MacOS/$PROJECT_NAME

if [ -d $EXECUTABLE.app ]; then
  $MAC_EXECUTABLE
else
  $EXECUTABLE
fi
